spring:
  application:
    name: msclientes

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}